# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Quiz.create(content: "上級問題２", level: 3)	
Quiz.create(content: "上級問題３", level: 3)	
Quiz.create(content: "上級問題４", level: 3)	
Quiz.create(content: "上級問題５", level: 3)

Question.create(quiz_id: 4, content: "The rise in the unemployment rate has finally begun to (        ).", choice_1: "narrow down", choice_2: "break away", choice_3: "parcel out", choice_4: "taper off", correct_answer: "taper off", explanation: "「taper off」で、「先細りになる」なので、正解は４です。")
Question.create(quiz_id: 4, content: "Let's take a few minutes to (	) and discuss again.", choice_1: "simmer down", choice_2: "bubble over", choice_3: "burn out", choice_4: "freeze over", correct_answer: "simmer down", explanation: "「simmer down」で、「落ち着く」なので、正解は１です。")
Question.create(quiz_id: 4, content: "I was interested in the production but balked at the high price.", choice_1: "その商品に興味あったが、値段の高さにびっくりした。", choice_2: "その商品に興味あったが、値段の高さに腹を立てた。", choice_3: "その商品に興味あったが、値段の高さにしり込みした。", choice_4: "その商品に興味あったが、後悔した。", correct_answer: "その商品に興味あったが、値段の高さにしり込みした。", explanation: "「balk at」で、「しり込みする」なので、正解は３です。")
Question.create(quiz_id: 4, content: "A habit is very difficult to shake off.", choice_1: "習慣を断ち切るのは難しい。", choice_2: "習慣をよくするのは、難しい。", choice_3: "習慣をつけるのは難しい。", choice_4: "習慣になれるのは難しい。", correct_answer: "習慣を断ち切るのは難しい。", explanation: "「shake off」で、「断ち切る」なので、正解は１です。")
Question.create(quiz_id: 4, content: "It's useless even if you butter up now.", choice_1: "今さらお世辞を言ったとしても意味ない。", choice_2: "今急いでも意味ない。", choice_3: "今さら嘆いても意味ない。", choice_4: "今さら誤っても意味ない。", correct_answer: "今お世辞を言ったとしても意味ない。", explanation: "「butter up」で、「お世辞を言う」なので、正解は１です。")
Question.create(quiz_id: 4, content: "It's useless even if you butter up now.", choice_1: "今さらお世辞を言ったとしても意味ない。", choice_2: "今急いでも意味ない。", choice_3: "今さら嘆いても意味ない。", choice_4: "今さら誤っても意味ない。", correct_answer: "今お世辞を言ったとしても意味ない。", explanation: "「butter up」で、「お世辞を言う」なので、正解は１です。")
Question.create(quiz_id: 4, content: "He was warned not to goof off.", choice_1: "彼は、遅刻するなと注意された。", choice_2: "彼は、不真面目なことをするなと注意された。", choice_3: "彼は、さぼるなと注意された。", choice_4: "彼は、物を壊すなと注意された。", correct_answer: "彼は、さぼるなと注意された。", explanation: "「goof off」で、「さぼる」なので、正解は３です。")

Question.create(quiz_id: 12, content: "In an effort to (	) security, the company hired more guards.", choice_1: "pass up", choice_2: "beef up", choice_3: "boil down", choice_4: "mark down", correct_answer: "beef up", explanation: "「beef up」で、「強化する」なので、正解は２です。")
Question.create(quiz_id: 12, content: "Recently prices of vegetables have (	  ).", choice_1: "shot up", choice_2: "blowned up", choice_3: "drawn up", choice_4: "marked up", correct_answer: "shot up", explanation: "「shot up」で、「急騰する」なので、正解は１です。")
Question.create(quiz_id: 12, content: "He passed the opportunity up to go to America.", choice_1: "彼はアメリカに行く機会を手に入れた。", choice_2: "彼はアメリカに行く機会を探した。", choice_3: "彼はアメリカに行く機会を逃した。", choice_4: "彼はアメリカに行く機会を求めた。", correct_answer: "彼はアメリカに行く機会を逃した。", explanation: "「pass up」で、「～を逃す」なので、正解は３です。")
Question.create(quiz_id: 12, content: "The best way to wind down is to take a hot bath.", choice_1: "風邪を治すには、お湯につかるのがベストだ。", choice_2: "緊張をほぐすには、お湯につかるのがベストだ。", choice_3: "イライラを鎮めるには、お湯につかるのがベストだ。", choice_4: "寒さを和らげるには、お湯につかるのがベストだ。", correct_answer: "緊張をほぐすには、お湯につかるのがベストだ。", explanation: "「wind down」で、「緊張をほぐす」なので、正解は２です。")
Question.create(quiz_id: 12, content: "I hope to get around to finishing the work.", choice_1: "仕事がうまく終わればいいんだけど。", choice_2: "仕事が終えるために協力できればいいんだけど。", choice_3: "仕事を終えるために話し合えればいいんだけど。", choice_4: "仕事を終えるとこまで手が回ればいいんだけど。", correct_answer: "仕事を終えるとこまで手が回ればいいんだけど。", explanation: "「get around to doing」で、「する余裕がある」なので、正解は４です。")
Question.create(quiz_id: 12, content: "They met to hammer out a breakthrough.", choice_1: "打開策を打ち出すために集まった。", choice_2: "打開策を見直すために集まった。", choice_3: "打開策の必要性を問うために集まった。", choice_4: "打開策の意見交換をするため集まった。", correct_answer: "打開策を打ち出すために集まった。", explanation: "「hammer out」で、「～を打ち出す」なので、正解は１です。")

Question.create(quiz_id: 13, content: "He can (		) articles very quickly.", choice_1: "grind up", choice_2: "skim off", choice_3: "nibble away", choice_4: "churn out", correct_answer: "churn out", explanation: "「churn out」で、「大量生産する、（文字を）書く」なので、正解は４です。")
Question.create(quiz_id: 13, content: "Every one (	) to the side of the road.", choice_1: "pass out", choice_2: "pull over", choice_3: "slip up", choice_4: "hang around", correct_answer: "pull over", explanation: "「pull over to」で、「～に寄る」なので、正解は２です。")
Question.create(quiz_id: 13, content: "She is tired to be fired away yesterday.", choice_1: "彼女は、昨日色々質問をされて疲れている。", choice_2: "彼女は昨日仕事が大変で疲れている。", choice_3: "彼女は昨日徹夜をして疲れている。", choice_4: "彼女は昨日大変な目にあって疲れている。", correct_answer: "彼女は、昨日色々質問をされて疲れている。", explanation: "「fire away」で、「どんどん質問する」なので、正解は１です。")
Question.create(quiz_id: 13, content: "She has no choice but to fall back on her mother.", choice_1: "彼女は母を頼りにするしかない。", choice_2: "彼女は、母に打ち明けるしかない。", choice_3: "彼女は、母に聞くしかない。", choice_4: "彼女は、母を手伝うしかない。", correct_answer: "彼女は母を頼りにするしかない。", explanation: "「fall back on」で、「～を頼る」なので、正解は１です。")
Question.create(quiz_id: 13, content: "She has been fishing for compliments about a ring her boyfrind bought to her.", choice_1: "彼女は、彼氏に買ってもらった指輪を自慢してきた。", choice_2: "彼女は、彼氏に買ってもらった指輪を長々と説明してきた。", choice_3: "彼女は、彼氏に買ってもらった指輪をそれとなく見せてきた。", choice_4: "彼女は、彼氏が買った指輪をほめてもらいたがっている。", correct_answer: "彼女は、彼氏が買った指輪をほめてもらいたがっている。", explanation: "「fish for」で、「それとなく求める」なので、正解は４です。")
Question.create(quiz_id: 13, content: "I'm not bank on his help anymore.", choice_1: "これ以上彼の助けを求めるわけにはいかない。", choice_2: "これ以上彼の助けを受けても仕方ない。", choice_3: "これ以上彼の助けはあてにしない。", choice_4: "これ以上彼の助けを必要としてはいけない。", correct_answer: "これ以上彼の助けはあてにしない。", explanation: "「bank on」で、「～を当てにする」なので、正解は３です。")

Question.create(quiz_id: 14, content: "It is doubtful that he will (	 ) considering his age.", choice_1: "pull through", choice_2: "chip in", choice_3: "flow over", choice_4: "shoot down", correct_answer: "pull through", explanation: "「pull through」で、「（病気などを）乗り切る」なので、正解は１です。")
Question.create(quiz_id: 14, content: "He always (	) when somebody is talking.", choice_1: "hungs back", choice_2: "sews up", choice_3: "butts in", choice_4: "spins off", correct_answer: "butts in", explanation: "「butt in」で、「口をはさむ」なので、正解は３です。")
Question.create(quiz_id: 14, content: "He shelled out money in order to achieve his goal.", choice_1: "目的を達成するには節約した。", choice_2: "目的を達成するために渋々お金を出した。", choice_3: "目的を達成するためにお金を集めた。", choice_4: "目的を達成するためにお金をお願いした。", correct_answer: "目的を達成するために渋々お金を出した。", explanation: "「shell out」で、「渋々お金を出す」なので、正解は２です。")
Question.create(quiz_id: 14, content: "Thank you for sticking up for me at that time.", choice_1: "あの時、いろいろ教えてくれてありがとう。", choice_2: "あの時、手を貸してくれてありがとう。", choice_3: "あの時アドバイスをくれてありがとう。", choice_4: "あの時僕をかばってくれてありがとう。", correct_answer: "あの時僕をかばってくれてありがとう。", explanation: "「stick up for」で、「かばう、支持する」なので、正解は４です。")
Question.create(quiz_id: 14, content: "He was warned not to goof off.", choice_1: "彼は、遅刻するなと注意された。", choice_2: "彼は、不真面目なことをするなと注意された。", choice_3: "彼は、さぼるなと注意された。", choice_4: "彼は、物を壊すなと注意された。", correct_answer: "彼は、さぼるなと注意された。", explanation: "「goof off」で、「さぼる」なので、正解は３です。")
Question.create(quiz_id: 14, content: "They met to hammer out a breakthrough.", choice_1: "打開策を打ち出すために集まった。", choice_2: "打開策を見直すために集まった。", choice_3: "打開策の必要性を問うために集まった。", choice_4: "打開策の意見交換をするため集まった。", correct_answer: "打開策を打ち出すために集まった。", explanation: "「hammer out」で、「～を打ち出す」なので、正解は１です。")

Question.create(quiz_id: 15, content: "The rise in the unemployment rate has finally begun to (        ).", choice_1: "narrow down", choice_2: "break away", choice_3: "parcel out", choice_4: "taper off", correct_answer: "taper off", explanation: "「taper off」で、「先細りになる」なので、正解は４です。")
Question.create(quiz_id: 15, content: "In an effort to (	) security, the company hired more guards.", choice_1: "pass up", choice_2: "beef up", choice_3: "boil down", choice_4: "mark down", correct_answer: "beef up", explanation: "「beef up」で、「強化する」なので、正解は２です。")
Question.create(quiz_id: 15, content: "The best way to wind down is to take a hot bath.", choice_1: "風邪を治すには、お湯につかるのがベストだ。", choice_2: "緊張をほぐすには、お湯につかるのがベストだ。", choice_3: "イライラを鎮めるには、お湯につかるのがベストだ。", choice_4: "寒さを和らげるには、お湯につかるのがベストだ。", correct_answer: "緊張をほぐすには、お湯につかるのがベストだ。", explanation: "「wind down」で、「緊張をほぐす」なので、正解は２です。")
Question.create(quiz_id: 15, content: "He shelled out money in order to achieve his goal.", choice_1: "目的を達成するには節約した。", choice_2: "目的を達成するために渋々お金を出した。", choice_3: "目的を達成するためにお金を集めた。", choice_4: "目的を達成するためにお金をお願いした。", correct_answer: "目的を達成するために渋々お金を出した。", explanation: "「shell out」で、「渋々お金を出す」なので、正解は２です。")
Question.create(quiz_id: 15, content: "She is tired to be fired away yesterday.", choice_1: "彼女は、昨日色々質問をされて疲れている。", choice_2: "彼女は昨日仕事が大変で疲れている。", choice_3: "彼女は昨日徹夜をして疲れている。", choice_4: "彼女は昨日大変な目にあって疲れている。", correct_answer: "彼女は、昨日色々質問をされて疲れている。", explanation: "「fire away」で、「どんどん質問する」なので、正解は１です。")
Question.create(quiz_id: 15, content: "She has no choice but to fall back on her mother.", choice_1: "彼女は母を頼りにするしかない。", choice_2: "彼女は、母に打ち明けるしかない。", choice_3: "彼女は、母に聞くしかない。", choice_4: "彼女は、母を手伝うしかない。", correct_answer: "彼女は母を頼りにするしかない。", explanation: "「fall back on」で、「～を頼る」なので、正解は１です。")